function Navbar()
{
  return `<nav>
  <a href="index.html">Home</a>
  <a href="Aboutus.html">About us</a>
  <a href="ourservices.html"> Our services</a>
  <a href="Patients&visitors.html">Patients & Visitors</a>
  <a href="GParea.html">GP Area</a>
  
  </nav>`;




}
function Footer1()
{
   return` <footer class="footer1">
   <div class="footer1imageswrap">
   <a href="https://www.nhs.uk/nhs-services/urgent-and-emergency-care-services/when-to-use-111/">
   <img class="Onelogo" src="Images/Call 111.png" alt="111logo">
   </a>
   
   <a href="https://www.blood.co.uk/">
       <img class="blood" src="Images/blood.png" alt="blood">
       </a>

       <a href="https://www.cqc.org.uk/">
           <img class="care" src="Images/care.png" alt="care">
           </a>

           <a href="https://www.organdonation.nhs.uk/">
               <img class="Organ" src="Images/Organ.png" alt="Organ">
               </a>

               <a href="https://www.organdonation.nhs.uk/">
                   <img class="Facebook" src="Images/Facebook.png" alt="Facebook">
                   </a>

                   <a href="https://www.organdonation.nhs.uk/">
                       <img class="Twitter" src="Images/Twitter.png" alt="Twitter">
                       </a>
   
                   </div>
 </footer>`


}
function Footer2()
{
  return`<footer class="footer2">

  <p>Terms of use</p> <p>Data Protection</p> <p>Accessibilty statement</p> <p>Site Map</p>  <p>Consultant</p>


</footer>`



}